<?php

namespace app\index\controller;

use think\App;
use think\facade\Session;
use think\Model;
use think\Request;

class User extends Container
{
    public $uid;

    public function __construct(App $app = null, Model $model = null)
    {
        parent::__construct($app, $model);
        $this->model = new \app\index\model\User();
        $this->uid = Session::get("uid");
    }

    public function zone()
    {
        $uid = Session::get("user_id");
    }

    /**
     * web环境下的手动登录
     * @param $username
     * @param $password
     * @param $verifyCode
     */
    public function login($username, $password, $verifyCode)
    {
        $data = $this->model->where(["username" => $username, "password" => $password])->where("yiban_openid is not null")->find();
        if (is_null($data)) return Error::login("账号密码错误");
        Session::set("user_id", $data->getData("id"));
        Session::set("user_data", $data->getData());
        return $this->response([], "ok");
    }

    /**
     *易班环境下的自动登录
     */
    public function autoLoginByYiBan()
    {

    }

    /**
     *微信环境下的自动登录
     */
    public function autoLoginByWX()
    {

    }

    /**
     * 绑定易班账号
     * @param $openid
     */
    public function registerByYiBan($openid)
    {

    }

    /**
     * 绑定易班账号
     * @param $openid
     */
    public function registerByWX($openid)
    {

    }

    public function update(Request $request, $id)
    {
        //todo overwrite User's 'update' method
        return parent::update($request, $id); // TODO: Change the autogenerated stub
    }

    private function setPwd($uid, $password)
    {
        return $this->model->save(["password" => md5($password)], $uid);
    }

    public function changePwd($oldPassword, $newPassword, $verifyCode)
    {
        $data = $this->model->where(["password" => md5($oldPassword), "uid" => $this->uid])->find();
        if (is_null($data)) return Error::login("原密码错误");
        $result = $this->setPwd($this->uid, $newPassword);
        return $this->response($result, "ok");
    }

    public function setEmail($email)
    {
        $result = $this->model->save(["email" => $email], $this->uid);
        return $this->response($result, "ok");
    }
}
